name: GitHub Commit Check

on:
  schedule:
    # Run at 6 PM UTC every day
    - cron: '0 18 * * *'
  workflow_dispatch:  # Allow manual triggering

jobs:
  check-activity:
    name: Check GitHub Activity
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install DUCK and dependencies
        run: |
          uv pip install --system .

      - name: Check for today's activity (commits/PRs)
        id: duck_check
        env:
          GITHUB_USERNAME: ${{ secrets.GITHUB_USERNAME }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          EMAIL_RECIPIENT: ${{ secrets.EMAIL_RECIPIENT }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
        run: |
          bash scripts/check_and_notify.sh

      - name: Generate email content
        if: ${{ failure() }}
        run: |
          python3 scripts/generate_email.py \
            --username "${{ secrets.GITHUB_USERNAME }}" \
            --message "No GitHub activity detected for today. Please make a commit or create a PR to maintain your streak!" \
            --output tmp/activity-reminder-output.html

      - name: Send notification if no activity
        if: ${{ failure() }}
        uses: dawidd6/action-send-mail@v5
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.SMTP_USER }}
          password: ${{ secrets.SMTP_PASSWORD }}

          subject: "DUCK: No GitHub Activity Today!"
          to: ${{ secrets.EMAIL_RECIPIENT }}
          from: DUCK Reminder <${{ secrets.SMTP_USER }}>
          html_body: file://tmp/activity-reminder-output.html

          priority: high
          ignore_cert: false
