name: GitHub Commit Check

on:
  schedule:
    # Run at 6 PM UTC every day
    - cron: '0 18 * * *'
  workflow_dispatch:  # Allow manual triggering

jobs:
  check-activity:
    name: Check GitHub Activity
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install DUCK and dependencies
        run: |
          uv pip install --system .

      - name: Create tmp directory
        run: mkdir -p tmp

      - name: Check for today's activity (commits/PRs)
        id: duck_check
        env:
          USERNAME: ${{ secrets.USERNAME }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          EMAIL_RECIPIENT: ${{ secrets.EMAIL_RECIPIENT }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
        run: |
          bash scripts/check_and_notify.sh || true

      - name: Send notification if no activity (backup method)
        if: ${{ env.EMAIL_SENT != 'true' && failure() }}
        uses: dawidd6/action-send-mail@v6
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.SMTP_USER }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: "DUCK: No GitHub Activity Today!"
          to: ${{ secrets.EMAIL_RECIPIENT }}
          from: DUCK Reminder <${{ secrets.SMTP_USER }}>
          body: |
            Hello @${{ secrets.USERNAME }},

            It looks like you haven't had any GitHub activity (commits or PRs) today.
            Don't be a DUCK! Time to make some contributions.

            Maintaining a consistent GitHub contribution streak is important for:
            - Building your developer portfolio
            - Staying engaged with your projects
            - Demonstrating your coding consistency
            - Learning and growing your skills daily

            This is an automated message from DUCK (Daily User Commit Keeper).
          priority: high
          ignore_cert: false
